### PR TITLE
Adding full PT-BR translation

### PR DESCRIPTION
**Pull request by tloriato**
#### Abstract:
I feel grateful for the opportunity of serving the Zcash Community by, this time, providing the translation to the 5th largest language in the world. And will be forever thankful to @ZcashFoundation for allowing me to participate in Zcon0.  

I understand the importance of a translation in sensitive software, even more so when it deals with both Privacy and the user's money. Because of that, I wanted to be as transparent as possible of the translation and the trade-offs that I had to make.

------------------------
##### How to Translated "Shielded"-related concepts:

We don't have in Portuguese a word that would be similar in the sense as the "shielded" concept in English. For that reason, I had to come the closest I could get while still briefly conveying the message. 

I opted to translate "shielded" as "_blindado_" which would be more similar to "armored" in English. This choice was made to preserve the "metaphorical" spirit while still holding the concept of something strong and protected. We do, however, have other choices: 

- _Privado_ -> private
- _Protegido_ -> protected
- _Anônimo_ -> anonymous

##### z-Addresses & t-Addresses:

I'm still not sure about this, but I chose to **not** translate any reference to those concepts. The problem here is that "Address" is translatable to "_Endereço_" but, in contrary to the English language, adjectives in Portuguese come after the noun, and it would end up something like "_Endereços Z_" and "_Endereços T_". You could, in any way, do something like this:

- "_z-Ender_", "_z-Endr_": The problem with the diminutives here is that they don't remind people at all of the word "_Endereço_" and the latter one is unpronounceable.  
- "_z-Endereços_": You could actually translate to that, although (_personal opinion_) it becomes a little long.

##### Memo Button:

I translated the "Memo" button when sending a transaction to "_Anexar Recado_". The first word, "_anexar_" is the Portuguese equivalent to attach (in the email sense) and the second one is something similar to "message" in the "Do you want to leave a message?" sense. 

----------------------

#### Other Choices Made:

- The "Address Book" button when sending a transaction was replaced with "_Agenda_" (Diary). The choice was made because "_Agenda de Endereços_" would be way too long for a button, but in every other instance I referred to it by its full name.

- The "Update Label" button, also when sending a transaction, was replaced with "_Atualizar Etiqueta_ " which is a proper translation, but it was shortened to "Atualizar" due to its 50%+ characters. 

- "Miner Fee" was basically changed to "Mining fee" during the translation, resulting in "_Taxa de mineração_". The reason for that it's because how the fee is perceived by the Brazilian community if that makes sense. In the last years that I've been following the community the usage of "mining fee" far outweighs the "miner fee" one.

- There was a shortcut bound to the "Exit" option in the File menu. The shortcut uses the letter X to quickly select that option. "Exit" is best translated to "_Sair_" but none of the letters in it are commonly associated with the act of quitting as opposed to "X". Because it has pretty strong side-effects, I opted to remove the shortcut functionality.

- "Copied to clipboard" was translated simply to "Copied", as the translation for clipboard is rarely used and not adequate, making even OS's just using the word "_Copiado_"

### CODE REVIEW

**Comment by adityapk00** [comment]
This is absolutely fantastic! Thanks a ton for this. I will merge it, and it will be in the release v0.5.2 tomorrow.

**Comment by adityapk00** [comment]
One question - Is Portuguese (Brazil) different from just a global Portuguese? Can I just add this for the "pr" locale, and use it for all Portuguese locales?

**Comment by tloriato** [comment]
It would be something close to American English vs British English, but a little stronger, IMO.

People might not know exactly the meaning intended for a specific word, but they are likely able to understand the context. 

I think it's alright to put as global Portuguese for now, but ideally you would have Portuguese from Portugual (pt-pt) and Brazilian Portuguese (pt-br)

**Comment by adityapk00** [comment]
Got it. So I think what I'll do is load this for both locales, and if in the future we want to draw out some distinctions between pt_br and pt_pt, we'll split the files. Sounds good?

**Comment by tloriato** [comment]
Sure!

**Comment by adityapk00** [comment]
Cool. And once again, thanks a ton for this!

**Pull request merged**
